global:
  scrape_interval: 2s # 2초마다 긁어오기 (실무에선 보통 10s~1m, 테스트니 짧게)

scrape_configs:
  - job_name: 'ticket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # host.docker.internal은 도커 컨테이너 안에서 내 컴퓨터(localhost)를 가리키는 주소
      - targets: ['host.docker.internal:8080']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']